#!/bin/bash
export LANG=en
count=20

function ddtest
{
    name=$1
    echo test $name
    rm /$name/dd.test* 2>/dev/null

    echo test $name write
    seq 1 $count| xargs -i{} bash -c "dd if=/dev/urandom of=/$name/dd.test.{} bs=1M count=1000 2>&1"|grep copied

    sleep 120;

    echo test $name read
    seq 1 $count| xargs -i{} bash -c "dd of=/dev/null if=/$name/dd.test.{} bs=1M 2>&1"|grep copied

    sleep 120;

    echo test $name write and read
    seq 1 $count| xargs -i{} bash -c "dd if=/$name/dd.test.{} of=/$name/dd.test.{}.w bs=1M count=1000 2>&1"|grep copied

    rm /$name/dd.test* 2>/dev/null
    echo done
}

ddtest c3sm
sleep 300;
ddtest c3smx
sleep 300;
ddtest c3smo
