#!/bin/bash

master=$(head -n 1 /data/c3sm/cluster/node.list);

init=$(cat /data/c3sm/cluster/node.list|head -n 2|xargs -n 2)
mydan rcall -r $master exec "/data/c3sm/server/tool/volumex/init $init"

cat /data/c3sm/cluster/node.list | sed 1,2d|xargs  -n 2|grep ' '|xargs -i{} mydan rcall -r $master exec '/data/c3sm/server/tool/volumex/addnode {}'
mydan rcall -r $master exec "/data/c3sm/server/tool/volumex/start"
mydan rcall -r $master exec "/data/c3sm/server/tool/volumex/performance"
mydan rcall -r $master exec "/data/c3sm/server/tool/volumex/status"
