#!/bin/bash

master=$(head -n 1 /data/c3sm/cluster/node.list);

nodes=$(cat /data/c3sm/cluster/node.list|xargs -i{} echo {}:/data/c3smo|xargs -n 1000)
nodec=$(cat /data/c3sm/cluster/node.list|wc -l)

mydan rcall -r $master exec "echo y|docker exec -i openc3-c3sm gluster volume create c3smo disperse $nodec redundancy 1 transport tcp $nodes force"

mydan rcall -r $master exec "/data/c3sm/server/tool/volumeo/start"
mydan rcall -r $master exec "/data/c3sm/server/tool/volumeo/performance"
mydan rcall -r $master exec "/data/c3sm/server/tool/volumeo/status"
