#!/bin/bash

nodes=$(cat /data/c3sm/cluster/node.list |/opt/mydan/dan/tools/range)

/opt/mydan/dan/tools/rcall -r $nodes exec 'cd /data/c3sm && git pull'
/opt/mydan/dan/tools/rcall -r $nodes exec '/data/c3sm/server/tool/Clean'
/opt/mydan/dan/tools/rcall -r $nodes exec '/data/c3sm/server/tool/docker/run'
/opt/mydan/dan/tools/rcall -r $nodes exec 'systemctl enable docker'
